language = "C"
include_guard = "USD_TOOLBOX_H"
pragma_once = true
documentation = true
usize_is_size_t = true
style = "both"
sort_by = "Name"

[parse]
parse_deps = false

[export]
include = [
  "UsdToolboxBuffer",
  "UsdToolboxStatus",
  "UsdToolboxTarget",
  "USD_TOOLBOX_TARGET_USDZ",
  "USD_TOOLBOX_TARGET_USDA",
  "USD_TOOLBOX_TARGET_USDC",
  "USD_TOOLBOX_TARGET_MATERIALX",
  "USD_TOOLBOX_TARGET_GLTF",
  "USD_TOOLBOX_TARGET_GLB",
  "USD_TOOLBOX_TARGET_REVIT",
  "USD_TOOLBOX_TARGET_OMNIVERSE",
]
