[package]
name = "usd-toolbox-gltf"
description = "glTF 2.0 and GLB material export for usd-toolbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
image.workspace = true
usd-toolbox-core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
