[package]
name = "usd-toolbox-wasm"
description = "WebAssembly bindings for usd-toolbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
usd-toolbox-core.workspace = true
usd-toolbox-gltf.workspace = true
usd-toolbox-materials.workspace = true
usd-toolbox-materialx.workspace = true
usd-toolbox-omniverse.workspace = true
usd-toolbox-revit.workspace = true
usd-toolbox-textures.workspace = true
usd-toolbox-usd.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
time.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
